service: groupee-bot-service

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  environment:
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):${opt:stage, 'dev'}.TELEGRAM_TOKEN}

functions:
  serve:
    handler: service.serve
    name: groupee-bot-transceiver
    description: Receives messages and replies to them from Telegram clients
    events:
      - http:
          path: /webhook
          method: post
          cors: true
    memorySize: 256
    timeout: 10

plugins:
  - serverless-offline
